/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as FeedRouteImport } from './routes/_feed'
import { Route as FeedIndexRouteImport } from './routes/_feed.index'
import { Route as FeedDailyRouteImport } from './routes/_feed.daily'
import { Route as FeedFavoritesRouteImport } from './routes/_feed.favorites'
import { Route as FeedYouRouteImport } from './routes/_feed.you'

const FeedRoute = FeedRouteImport.update({
  id: '/_feed',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedIndexRoute = FeedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => FeedRoute,
} as any)
const FeedDailyRoute = FeedDailyRouteImport.update({
  id: '/daily',
  path: '/daily',
  getParentRoute: () => FeedRoute,
} as any)
const FeedFavoritesRoute = FeedFavoritesRouteImport.update({
  id: '/favorites',
  path: '/favorites',
  getParentRoute: () => FeedRoute,
} as any)
const FeedYouRoute = FeedYouRouteImport.update({
  id: '/you',
  path: '/you',
  getParentRoute: () => FeedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof FeedIndexRoute
  '/daily': typeof FeedDailyRoute
  '/favorites': typeof FeedFavoritesRoute
  '/you': typeof FeedYouRoute
}
export interface FileRoutesByTo {
  '/daily': typeof FeedDailyRoute
  '/favorites': typeof FeedFavoritesRoute
  '/you': typeof FeedYouRoute
  '/': typeof FeedIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_feed': typeof FeedRouteWithChildren
  '/_feed/daily': typeof FeedDailyRoute
  '/_feed/favorites': typeof FeedFavoritesRoute
  '/_feed/you': typeof FeedYouRoute
  '/_feed/': typeof FeedIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/daily' | '/favorites' | '/you'
  fileRoutesByTo: FileRoutesByTo
  to: '/daily' | '/favorites' | '/you' | '/'
  id:
    | '__root__'
    | '/_feed'
    | '/_feed/daily'
    | '/_feed/favorites'
    | '/_feed/you'
    | '/_feed/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  FeedRoute: typeof FeedRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_feed': {
      id: '/_feed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof FeedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_feed/': {
      id: '/_feed/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof FeedIndexRouteImport
      parentRoute: typeof FeedRoute
    }
    '/_feed/daily': {
      id: '/_feed/daily'
      path: '/daily'
      fullPath: '/daily'
      preLoaderRoute: typeof FeedDailyRouteImport
      parentRoute: typeof FeedRoute
    }
    '/_feed/favorites': {
      id: '/_feed/favorites'
      path: '/favorites'
      fullPath: '/favorites'
      preLoaderRoute: typeof FeedFavoritesRouteImport
      parentRoute: typeof FeedRoute
    }
    '/_feed/you': {
      id: '/_feed/you'
      path: '/you'
      fullPath: '/you'
      preLoaderRoute: typeof FeedYouRouteImport
      parentRoute: typeof FeedRoute
    }
  }
}

interface FeedRouteChildren {
  FeedDailyRoute: typeof FeedDailyRoute
  FeedFavoritesRoute: typeof FeedFavoritesRoute
  FeedYouRoute: typeof FeedYouRoute
  FeedIndexRoute: typeof FeedIndexRoute
}

const FeedRouteChildren: FeedRouteChildren = {
  FeedDailyRoute: FeedDailyRoute,
  FeedFavoritesRoute: FeedFavoritesRoute,
  FeedYouRoute: FeedYouRoute,
  FeedIndexRoute: FeedIndexRoute,
}

const FeedRouteWithChildren = FeedRoute._addFileChildren(FeedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  FeedRoute: FeedRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
